config/routes.rb
Rails.application.routes.draw do

  resources :restaurants, except: :destroy do
    resources :reviews, only: [:new, :create,]
  end

root 'restaurants#recentlyadded'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
has_many :reviews

validates :name, presence: true
validates :address, presence: true
validates :city, presence: true
validates :state, presence: true
validates :zipcode, presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant

  validates :rating, inclusion: (1..5), presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurant = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @new_restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    Restaurant.destroy(params[:id])
    redirect_to restaurants_path
  end

  def recentlyadded
    @restaurants = Restaurant.limit(10)
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :city, :state, :zipcode, :description, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index

  end

  def show

  end

  def new

  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])

    @review = Review.new(review_params)

    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoodEats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/edit.html.erb
<h1>Add new Restaurant</h1>

<%= form_for @new_restaurant do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
  </div>
  <div>
    <%= f.label :address %>
    <%= f.text_field :address %><br>
  </div>
  <div>
    <%= f.label :city %>
    <%= f.text_field :city %><br>
  </div>
  <div>
    <%= f.label :state %>
    <%= f.text_field :state %><br>
  </div>
  <div>
    <%= f.label :zipcode %>
    <%= f.text_field :zipcode %><br>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description %><br>
  </div>
  <div>
    <%= f.label :category %>
    <%= f.text_field :category %><br>
  </div>

  <%= f.submit %>

<% end %>

app/views/restaurants/index.html.erb
<ul>
  <% @restaurant.each do |restaurant|%>
    <li><%= link_to(restaurant.name, restaurant_path(restaurant)) %></li>
  <% end %>
</ul>

<%= link_to 'Add new restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>Add new Restaurant</h1>

<%= form_for @new_restaurant do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
  </div>
  <div>
    <%= f.label :address %>
    <%= f.text_field :address %><br>
  </div>
  <div>
    <%= f.label :city %>
    <%= f.text_field :city %><br>
  </div>
  <div>
    <%= f.label :state %>
    <%= f.text_field :state %><br>
  </div>
  <div>
    <%= f.label :zipcode %>
    <%= f.text_field :zipcode %><br>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description %><br>
  </div>
  <div>
    <%= f.label :category %>
    <%= f.text_field :category %><br>
  </div>

  <%= f.submit %>

<% end %>

app/views/restaurants/recentlyadded.html.erb
<h1>Good Eats</h1>
<ul>
  <% @restaurants.each do |restaurant|%>
    <li><%= link_to(restaurant.name, restaurant_path(restaurant)) %></li>
  <% end %>
</ul>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<p><%= @restaurant.address %><br>
  <%= @restaurant.city %>, <%= @restaurant.state %> <%= @restaurant.zipcode %></p>

<p><%= @restaurant.description %></p>
<p><%= @restaurant.category %></p>

<h2>Add a Review</h2>

<br><br>

<ul>
  <% @restaurant.reviews.order(created_at: :desc).each do |review| %>
    <li><%= review.rating %> - <%= review.body %></li>
  <% end %>
</ul>



<%= form_for [@restaurant, @review] do |f| %>
  <div>
    <%= f.label "Rating: 1-5" %>
    <%= f.text_field :rating, placeholder: "Enter rating" %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_field :body, placeholder: "Enter review" %>
  </div>

  <%= f.submit %>
<% end %>


<!-- buttons -->

<%= link_to 'Delete Restaurant', restaurant_path(@restaurant), method: :delete %><br>

<%= link_to 'Back to Restaurants', restaurants_path %>